/**
 * Network diff service
 * Network diff service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';


import { NetworkDiffResponse } from '../model/networkDiffResponse';
import { NetworkIds } from '../model/networkIds';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { Observable } from 'rxjs';


@Injectable()
export class ApiService {

    protected basePath = 'http://localhost:6007/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * List network ids
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public networksGet(observe?: 'body', reportProgress?: boolean): Observable<NetworkIds>;
    public networksGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NetworkIds>>;
    public networksGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NetworkIds>>;
    public networksGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<NetworkIds>(`${this.basePath}/networks`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Check transaction status
     * 
     * @param network1Uuid first network id
     * @param network2Uuid second network id
     * @param vlId voltage level id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public networksNetwork1UuidDiffNetwork2UuidVlVlIdPost(network1Uuid: string, network2Uuid: string, vlId: string, observe?: 'body', reportProgress?: boolean): Observable<NetworkDiffResponse>;
    public networksNetwork1UuidDiffNetwork2UuidVlVlIdPost(network1Uuid: string, network2Uuid: string, vlId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NetworkDiffResponse>>;
    public networksNetwork1UuidDiffNetwork2UuidVlVlIdPost(network1Uuid: string, network2Uuid: string, vlId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NetworkDiffResponse>>;
    public networksNetwork1UuidDiffNetwork2UuidVlVlIdPost(network1Uuid: string, network2Uuid: string, vlId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (network1Uuid === null || network1Uuid === undefined) {
            throw new Error('Required parameter network1Uuid was null or undefined when calling networksNetwork1UuidDiffNetwork2UuidVlVlIdPost.');
        }

        if (network2Uuid === null || network2Uuid === undefined) {
            throw new Error('Required parameter network2Uuid was null or undefined when calling networksNetwork1UuidDiffNetwork2UuidVlVlIdPost.');
        }

        if (vlId === null || vlId === undefined) {
            throw new Error('Required parameter vlId was null or undefined when calling networksNetwork1UuidDiffNetwork2UuidVlVlIdPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<NetworkDiffResponse>(`${this.basePath}/networks/${encodeURIComponent(String(network1Uuid))}/diff/${encodeURIComponent(String(network2Uuid))}/vl/${encodeURIComponent(String(vlId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
