/**
 * Network diff service
 * Network diff service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VoltageLevelDiff } from './voltageLevelDiff';


export interface NetworkDiffResponse {
    network1 : string,
    network2 : string,
    "diff.VoltageLevels": VoltageLevelDiff[]
}
